language: python
dist: focal
arch:
  - arm64

python:
  - "3.8"
install:
  - uname -m
  - sudo apt-get -y install python3-pip
  - sudo apt-get -y install gcc
  - sudo apt-get -y install libffi-dev 
  - sudo pip3 install cffi
  - sudo apt-get -y install python3-dev python3.8-dev 
  - sudo apt -y install libpython3.8-dev
  - sudo python3 -m pip install --upgrade pip setuptools wheel
  - sudo pip3 install testresources
  - sudo apt install -y libgirepository1.0-dev
  - sudo apt install -y libcairo2 libcairo2-dev libglib2.0-dev libffi-dev libcairo-gobject2
  - sudo pip3 install Ninja 
  - sudo apt-get -y install xvfb
  - sudo apt-get update
  - sudo apt-get -y install build-essential libcairo2-dev libpango1.0-dev libjpeg-dev libgif-dev librsvg2-dev
  - sudo pip3 install pycairo
  - sudo python3 setup.py install
  
script:
  - sudo bash -x ./.gitlab-ci/test-docker.sh
